CREATE CATALOG batch_test WITH (
'type' = 'hive',
'default-database' = 'dwd',
'hive-conf-dir' = '/Users/renzhuo/IdeaProjects/Flink_test/src/main/resources'
);
create table employee_dimission(
    pk_date string,
    staff_record_id string,
    employee_id string,
    employee_name string,
    old_position_id string,
    old_position_name string,
    old_emp_level_chinese string,
    old_employee_type_chinese string,
    dimission_date string,
    dimission_type_chinese string,
    dimission_nature string,
    reason1 string,
    reason2 string,
    reason3 string,
    reason1_chinese string,
    reason1_chinese_desc string,
    record_time string,
    record_end_time string,
    record_type string,
    dimission_reason_desc string,
    new_unit_id string,
    old_unit_id string,
    new_employee_status string,
    old_employee_status string,
    old_employee_type string,
    new_employee_type string,
    old_unit_path_name string,
    new_unit_path_name string,
    old_emp_level string,
    new_emp_level string,
    old_job_group string,
    old_job_family_name string,
    old_job_type_chinese string,
    old_department string,
    old_department_fl string,
    old_department_level int,
    old_level1 string,
    old_level2 string,
    old_level3 string,
    old_level4 string,
    old_level5 string
)WITH (
'connector' = 'jdbc',
'url' = 'jdbc:mysql://172.22.17.38:3306/dap',
'table-name' = 'employee_dimission',
'driver' = 'com.mysql.cj.jdbc.Driver',
'username' = 'testdap',
'password' = 'h6jtcY_8PepE',
'sink.buffer-flush.max-rows' = '10000',
'sink.buffer-flush.interval' = '200ms',
'sink.max-retries' = '3'
);
insert into employee_dimission
select * from batch_test.dwd.employee_dimission